language: python
python:
  - "2.7"
  - "3.3"

install:
  - pip install .

script:
  - yasha --help
  - make -C tests/makefile_for_c
  - touch tests/makefile_for_c/foo.c.jinja
  - make -C tests/makefile_for_c
