language: python
python:
  - "2.7"
  - "3.3"

install:
  - pip install .

script:
  - py.test -v tests
  - yasha tests/fixtures/nrf51.rs.jinja
  - cmp -s tests/fixtures/nrf51.rs tests/fixtures/nrf51.rs.expected
