language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install .

script:
  - py.test -v tests
  - yasha tests/fixtures/nrf51.rs.jinja
  - cmp -s tests/fixtures/nrf51.rs tests/fixtures/nrf51.rs.expected
  - test -f tests/fixtures/nrf51.rs.j2extc || test -d tests/fixtures/__pycache__ # issue 4
